# Generated by Django 2.1 on 2018-08-30 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='course.Chapter'),
        ),
        migrations.AddField(
            model_name='section',
            name='preconditions',
            field=models.ManyToManyField(blank=True, to='course.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='tags',
            field=models.ManyToManyField(related_name='sections', to='course.Tag'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Section'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='enrollmentsectionpass',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Enrollment'),
        ),
        migrations.AddField(
            model_name='enrollmentsectionpass',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='passed_sections',
            field=models.ManyToManyField(blank=True, related_name='enrollments', through='course.EnrollmentSectionPass', to='course.Section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='course.Category'),
        ),
        migrations.AddField(
            model_name='course',
            name='preconditions',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='course.Enrollment', to='member.Student'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='preconditions',
            field=models.ManyToManyField(blank=True, to='course.Chapter'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('chapter', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('section', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order')},
        ),
    ]
