# Generated by Django 2.1 on 2018-09-12 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0006_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
            ],
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='NotificationsObjEMail',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.Notification')),
            ],
            bases=('notifications.notification',),
        ),
    ]
